export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const ALL_POST_REQUEST = 'ALL_POST_REQUEST'
export const ALL_POST_SUCCESS = 'ALL_POST_SUCCESS'
export const ALL_POST_FAIL = 'ALL_POST_FAIL'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_RESET = 'CREATE_POST_RESET'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'
export const USER_FOLLOW_RESET = 'USER_FOLLOW_RESET'

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST'
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS'
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL'
export const USER_UNFOLLOW_RESET = 'USER_UNFOLLOW_RESET'

export const USER_POST_REQUEST = 'USER_POST_REQUEST'
export const USER_POST_SUCCESS = 'USER_POST_SUCCESS'
export const USER_POST_FAIL = 'USER_POST_FAIL'

export const SINGLE_POST_REQUEST = 'SINGLE_POST_REQUEST'
export const SINGLE_POST_SUCCESS = 'SINGLE_POST_SUCCESS'
export const SINGLE_POST_FAIL = 'SINGLE_POST_FAIL'

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'
export const LIKE_POST_RESET = 'LIKE_POST_RESET'

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL'
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET'

export const POST_OF_USER_REQUEST = 'POST_OF_USER_REQUEST'
export const POST_OF_USER_SUCCESS = 'POST_OF_USER_SUCCESS'
export const POST_OF_USER_FAIL = 'POST_OF_USER_FAIL'

export const USER_PHOTO_REQUEST = 'USER_PHOTO_REQUEST'
export const USER_PHOTO_SUCCESS = 'USER_PHOTO_SUCCESS'
export const USER_PHOTO_FAIL = 'USER_PHOTO_FAIL'
export const USER_PHOTO_RESET = 'USER_PHOTO_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_PASSWORD_REQUEST = 'USER_PASSWORD_REQUEST'
export const USER_PASSWORD_SUCCESS = 'USER_PASSWORD_SUCCESS'
export const USER_PASSWORD_FAIL = 'USER_PASSWORD_FAIL'
export const USER_PASSWORD_RESET = 'USER_PASSWORD_RESET'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET'

